name: lint

on:
  pull_request:
    branches:
      - master

jobs:
  lint_python:

    runs-on: ${{ matrix.os }}
    timeout-minutes: 5
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.12.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - uses: astral-sh/setup-uv@v6
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: uv sync --frozen --only-group linters

      - run: shopt -s globstar && uv run pyupgrade --py312-plus **/*.py

      - run: uv run ruff format --diff .

      - run: uv run codespell . --ignore-words .codespellignore

      - run: uv run deptry .
